# Uncomment the next line to define a global platform for your project
# platform :ios, '13.4'

target 'assign5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for assign5
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
end
